project:
  type: website

website:
  title: KrisanatA.
  reader-mode: true
  navbar:
    logo: "images/icon.png"
    left:
      - text: Home
        href: index.qmd
      - text: Blog
        href: blog.qmd
      - text: About
        href: about.qmd
    right:
      - icon: github
        href: https://github.com/KrisanatA
format:
  html:
    theme: solar
    css: styles.css



